name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish tags as releases.
    tags:
      - '*'

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: postgres-backup

jobs:
  # Push image to GitHub Container Registry.
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID

          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            RELEASE_VERSION="$GITHUB_REF_NAME"
            NORMALIZED_VERSION="${RELEASE_VERSION#v}"

            echo RELEASE_VERSION=$RELEASE_VERSION

            docker tag "$IMAGE_NAME" "$IMAGE_ID:$RELEASE_VERSION"
            docker push "$IMAGE_ID:$RELEASE_VERSION"

            if [ "$NORMALIZED_VERSION" != "$RELEASE_VERSION" ]; then
              echo NORMALIZED_VERSION=$NORMALIZED_VERSION
              docker tag "$IMAGE_NAME" "$IMAGE_ID:$NORMALIZED_VERSION"
              docker push "$IMAGE_ID:$NORMALIZED_VERSION"
            fi
          else
            docker tag "$IMAGE_NAME" "$IMAGE_ID:latest"
            docker push "$IMAGE_ID:latest"
          fi
